kind: Service
apiVersion: v1
metadata:
  name: springboot-service
  labels:
    name: springboot-service
    app: cata-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080

  selector:
    name: springboot-pod
    app: cata-app
