apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deploy
  labels:
    name: springboot-deploy
    app: cata-app
spec:
  selector:
    matchLabels:
      app: cata-app
      name: springboot-pod
  replicas: 3
  template:
    metadata:
      name: springboot-pod
      labels:
        name: springboot-pod
        app: cata-app
    spec:
      containers:
        - name: cata-app
          image: icata04/spring-boot-postgresql:1.1
          ports:
            - containerPort: 8080
#          env:   # Setting Enviornmental Variables
#            - name: DB_HOST   # Setting Database host address from configMap
#              valueFrom:
#                configMapKeyRef:
#                  name: postgres-conf  # name of configMap
#                  key: host
#            - name: DB_NAME  # Setting Database name from configMap
#              valueFrom:
#                configMapKeyRef:
#                  name: postgres-conf
#                  key: name
#            - name: POSTGRES_USER  # Setting Database username from Secret
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-credentials # Secret Name
#                  key: postgres_user
#            - name: POSTGRES_PASSWORD # Setting Database password from Secret
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-credentials
#                  key: postgres_password
